
CREATE TABLE employees (
	id INT PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(300) NOT NULL,
	last_name VARCHAR(300) NOT NULL,
	birthdate DATE NOT NULL,
-- 	email VARCHAR(200) REFERENCES intranet_accounts ON DELETE 
	email VARCHAR(200) UNIQUE NOT NULL,
    team_id INT REFERENCES teams ON DELETE SET NULL
);
CREATE TABLE intranet_accounts (
	id INT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(200) REFERENCES employees (email) ON DELETE CASCADE,
	password VARCHAR(200) NOT NULL
);
CREATE TABLE comapny_buildings (
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(300) NOT NULL
);

CREATE TABLE teams (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(300) NOT NULL,
    building_id INT REFERENCEs company_buildings ON DELETE SET NULL
)